// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "Jag1":return img`
................................
................................
......cccffffffcccccf...........
.....fffffffcacaaaaaccffffffc...
...fffcfccaaaaaaaacccfffccaacf..
..ffcaaaaaaacccfccaaaaaaaaaacff.
.ffcaacffffccaaacffcccccaaaacff.
.fcaaaacaccacaaaafffaaacaaaafff.
.faacaacaaaacaaaafffaacaccaafff.
.faccaaccaaaaaaaaafccfcacaacfff.
.cacaaaacaaaaaaaaaccfffaaacffff.
.caaaaaacaacaaaaaccffffacfffcff.
.caaacaacaacccaaacccfffffffcaff.
.facaacacaaacaaaafcffffffffaaff.
.fcaaacccaacaaaaaffcccccffcacf..
.fcaaafcccacaaacccfcacccfaaaff..
..faaaaccccccaacacfcaccfcaacf...
..faaaaafffccacacacfffffaaaff...
..fccaaaafffccfffcfffffcaacff...
..fcaaaaaaffcccfccfffcaaaaacf...
...fcaaaaaafcaaaacffccaaaaacf...
...ffaaaaaacfaaaaffffcccacac....
....fccaaaacfccccf..fffccfcf....
....ffcaaaaafffff....f.ffff.....
....ffaaaaaacf..................
....fcaaaaaaaff.................
....faaaaaaaacf.................
....fccacaacacf.................
....fccacaaccff.................
....fffcffcfcc..................
........ffff....................
................................
`;
            case "image3":
            case "Jag2":return img`
................................
................................
...........fcccccffffffccc......
...cffffffccaaaaacacfffffff.....
..fcaaccfffcccaaaaaaaaccfcfff...
.ffcaaaaaaaaaaccfcccaaaaaaacff..
.ffcaaaacccccffcaaaccffffcaacff.
.fffaaaacaaafffaaaacaccacaaaacf.
.fffaaccacaafffaaaacaaaacaacaaf.
.fffcaacacfccfaaaaaaaaaccaaccaf.
.ffffcaaafffccaaaaaaaaacaaaacac.
.ffcfffcaffffccaaaaacaacaaaaaac.
.ffacfffffffcccaaacccaacaacaaac.
.ffaaffffffffcfaaaacaaacacaacaf.
..fcacffcccccffaaaaacaacccaaacf.
..ffaaafcccacfcccaaacacccfaaacf.
...fcaacfccacfcacaaccccccaaaaf..
...ffaaafffffcacacaccfffaaaaaf..
...ffcaacfffffcfffccfffaaaaccf..
...fcaaaaacfffccfcccffaaaaaacf..
...fcaaaaaccffcaaaacfaaaaaacf...
....cacacccffffaaaafcaaaaaaff...
....fcfccfff..fccccfcaaaaccf....
.....ffff.f....fffffaaaaacff....
..................fcaaaaaaff....
.................ffaaaaaaacf....
.................fcaaaaaaaaf....
.................fcacaacaccf....
.................ffccaacaccf....
..................ccfcffcfff....
....................ffff........
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "myAnim1":
            case "anim3":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "myAnim0":
            case "anim2":return [img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
